export const authErrorMessages_HR = {
    anonymous_provider_disabled: 'Anonimne prijave su onemogućene.',
    bad_code_verifier: 'Kod provjere ne odgovara očekivanom. Provjerite implementaciju klijenta.',
    bad_json: 'Tijelo zahtjeva nije ispravan JSON.',
    bad_jwt: 'JWT u zaglavlju Authorization nije valjan.',
    bad_oauth_callback: 'OAuth povratni poziv nema sve potrebne atribute (state). Provjerite OAuth integraciju.',
    bad_oauth_state: 'OAuth state nije u ispravnom formatu. Provjerite integraciju s OAuth pružateljem.',
    captcha_failed: 'Captcha izazov nije potvrđen. Provjerite integraciju s captcha pružateljem.',
    conflict: 'Sukob u bazi podataka. Provjerite probleme s konkurencijom u vašoj aplikaciji.',
    email_address_not_authorized: 'Slanje emaila nije dopušteno za ovu adresu.',
    email_conflict_identity_not_deletable: 'Korisnički račun s ovom email adresom već postoji.',
    email_exists: 'Email adresa već postoji u sustavu.',
    email_not_confirmed: 'Email adresa nije potvrđena.',
    email_provider_disabled: 'Registracija putem emaila i lozinke je onemogućena.',
    flow_state_expired: 'PKCE stanje je isteklo. Ponovno zatražite prijavu korisnika.',
    flow_state_not_found: 'PKCE stanje više ne postoji. Zatražite ponovno prijavu.',
    hook_payload_over_size_limit: 'Payload premašuje maksimalno dopuštenu veličinu.',
    hook_timeout: 'Vrijeme za izvršavanje hooka je isteklo.',
    hook_timeout_after_retry: 'Maksimalni broj pokušaja za hook je dosegnut.',
    identity_already_exists: 'Identitet je već povezan s korisnikom.',
    identity_not_found: 'Identitet ne postoji.',
    insufficient_aal: 'Korisnik mora imati višu razinu autentifikacije.',
    invite_not_found: 'Pozivnica je istekla ili već iskorištena.',
    invalid_credentials: 'Neispravni podaci za prijavu.',
    manual_linking_disabled: 'Ručna poveznica korisnika nije omogućena na Auth serveru.',
    mfa_challenge_expired: 'MFA izazov je istekao. Zatražite novi izazov.',
    mfa_factor_name_conflict: 'MFA faktori ne smiju imati isto ime.',
    mfa_factor_not_found: 'MFA faktor više ne postoji.',
    mfa_ip_address_mismatch: 'IP adresa mora biti ista na početku i kraju MFA procesa.',
    mfa_verification_failed: 'MFA provjera nije uspjela. Pogrešan TOTP kod.',
    mfa_verification_rejected: 'Daljnja MFA provjera je odbijena.',
    mfa_verified_factor_exists: 'Potvrđeni telefonski faktor već postoji.',
    mfa_totp_enroll_disabled: 'Upis MFA TOTP faktora je onemogućen.',
    mfa_totp_verify_disabled: 'Provjera MFA TOTP faktora je onemogućena.',
    mfa_phone_enroll_disabled: 'Upis MFA telefonskih faktora je onemogućen.',
    mfa_phone_verify_disabled: 'Provjera MFA telefonskih faktora je onemogućena.',
    no_authorization: 'Zaglavlje Authorization nije pruženo.',
    not_admin: 'Korisnik nije administrator.',
    oauth_provider_not_supported: 'OAuth pružatelj je onemogućen.',
    otp_disabled: 'Prijava putem OTP-a je onemogućena.',
    otp_expired: 'OTP kod je istekao. Pokušajte ponovno.',
    over_email_send_rate_limit: 'Previše emailova poslano. Pričekajte prije ponovnog pokušaja.',
    over_request_rate_limit: 'Previše zahtjeva poslano s ove IP adrese. Pričekajte prije ponovnog pokušaja.',
    over_sms_send_rate_limit: 'Previše SMS-ova poslano na ovaj broj. Pričekajte prije ponovnog pokušaja.',
    phone_exists: 'Telefonski broj već postoji u sustavu.',
    phone_not_confirmed: 'Telefonski broj nije potvrđen.',
    phone_provider_disabled: 'Registracija putem telefonskog broja je onemogućena.',
    provider_disabled: 'OAuth pružatelj je onemogućen.',
    provider_email_needs_verification: 'Potreban je email za verifikaciju nakon OAuth prijave.',
    reauthentication_needed: 'Potrebna je ponovna autentifikacija za promjenu lozinke.',
    reauthentication_not_valid: 'Ponovna autentifikacija nije uspjela. Unesite novi kod.',
    request_timeout: 'Zahtjev je predugo trajao. Pokušajte ponovno.',
    same_password: 'Nova lozinka mora biti različita od trenutne.',
    session_not_found: 'Sesija više ne postoji.',
    signup_disabled: 'Registracija novih korisnika je onemogućena.',
    single_identity_not_deletable: 'Korisnik mora imati barem jedan identitet.',
    sms_send_failed: 'Slanje SMS-a nije uspjelo. Provjerite postavke pružatelja usluge.',
    sso_domain_already_exists: 'SSO domena već postoji.',
    sso_provider_not_found: 'SSO pružatelj nije pronađen.',
    too_many_enrolled_mfa_factors: 'Previše MFA faktora je upisano.',
    unexpected_failure: 'Došlo je do neočekivane pogreške.',
    user_already_exists: 'Korisnik s ovim podacima već postoji.',
    user_banned: 'Korisnik je blokiran.',
    user_not_found: 'Korisnik ne postoji.',
    user_sso_managed: 'Polja korisnika se ne mogu mijenjati kod SSO prijave.',
    validation_failed: 'Pruženi parametri nisu u ispravnom formatu.',
    weak_password: 'Lozinka ne zadovoljava kriterije sigurnosti.',
};